name: PowerGems
version: '${project.version}'
main: dev.iseal.powergems.PowerGems
api-version: '1.20'
author: ISeal
load: STARTUP
depend: [SealLib]
softdepend: [WorldGuard, CombatLogX]
libraries:
  - com.mysql:mysql-connector-j:8.4.0
  - org.xerial:sqlite-jdbc:3.46.1.3
  - com.zaxxer:HikariCP:5.1.0
commands:
  getallgems:
    description: Command to give yourself all gems
    usage: /getallgems
    permission: powergems.getallgems
  setgem:
    description: Command to set your current flux
    usage: /setgem <gem> [level] [player]
    permission: powergems.setgem
  giveallplayersgem:
    description: Command to give everyone a gem
    usage: /giveallplayersgem <gem>
    permission: powergems.giveallplayersgem
  checkupdates:
    description: Command to check for updates
    usage: /checkupdates
    permission: powergems.checkupdates
  reloadconfig:
    description: Command to reload the config files
    usage: /reloadconfig
    aliases: [rc]
    permission: powergems.reloadconfig
  pgDebug:
    description: Debug command
    usage: /pgDebug
    aliases: [pgd, pgdb]
    permission: powergems.debug
  selectflux:
    description: Opens the flux selector GUI
    usage: /selectflux
    permission: powergems.fluxplus
permissions:
    powergems.movegems:
      description: Permission to move gems
      default: op
    powergems.getallgems:
        description: Permission to use /getallgem
        default: op
    powergems.setgem:
        description: Permission to use /setgem
        default: op
    powergems.giveallplayersgem:
        description: Permission to use /giveallgem
        default: op
    powergems.checkupdates:
        description: Permission to use /checkupdates
        default: op
    powergems.reloadconfig:
        description: Permission to use /reloadconfig
        default: op
    powergems.debug:
        description: Permission to use /debug
        default: op
    powergems.admin:
        description: Permission to receive admin messages
        default: op
    powergems.fluxplus:
        description: Permission to use /selectflux
        default: op
    powergems.*:
        description: Permission to use all PowerGems commands
        default: op
        children:
            powergems.getallgems: true
            powergems.setgem: true
            powergems.giveallplayersgem: true
            powergems.checkupdates: true
            powergems.reloadconfig: true
            powergems.debug: true
            powergems.movegems: true
            powergems.admin: true
            powergems.fluxplus: true
